METADB = 0
NAME2ID = 1
ID2NAME = 2
WIKI_NER = 3
ID2UID = 4
SENTENCE = 5

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

IGNORE_NER_TAG = ('O', 'DATE', 'NUMBER', 'ORDINAL', 'PERCENT', 'MONEY', 'DURATION')  # Non-NER tag
